### ISSUE TITLE
在Mac上破壳IPA运行时间过长，且无报错

### ISSUE THREAD

**Issue by YYAppleFan** [paradiseduo/appdecrypt#10]
如题，时间过长指30分钟。
Mac信息：
MacBook Air (M1, 2020)，macOS Big Sur 11.5.2;
IPA信息：
明日方舟，版本1.5.60，来源：借由 Apple Configurator 2 下载的适用于 iPhone 的 IPA 文件，MacO文件大小：159.6MB；
Appdecrypt 安装方式：
通过 Release 界面下载，解压后置于/usr/local/bin
终端界面如下：
Last login: Sat Aug 28 21:15:40 on ttys000
yy@YYdeMacBook-Air ~ % appdecrypt /Users/yy/Desktop/Arknights/Payload/arknights.app /Users/yy/Downloads

**Comment by paradiseduo** [comment]
iPhone上下载的APP只能在iPhone上砸壳

**Comment by YYAppleFan** [comment]
了解，谢谢
