### ISSUE TITLE
iPhone:~ root# appdecrypt /var/containers/Bundle/Application/6EAF497A-E921-4BB7-9006-F7FB6D813003/ ./        Success to copy file. Dump /var/containers/Bundle/Application/6EAF497A-E921-4BB7-9006-F7FB6D813003/QQNews.app/QQNews fail, because of encrypted fail with Operation not permitted

### ISSUE THREAD

**Issue by lgq2015** [paradiseduo/appdecrypt#15]
iPhone:~ root# appdecrypt /var/containers/Bundle/Application/6EAF497A-E921-4BB7-9006-F7FB6D813003/ ./       
Success to copy file.
Dump /var/containers/Bundle/Application/6EAF497A-E921-4BB7-9006-F7FB6D813003/QQNews.app/QQNews fail, because of encrypted fail with Operation not permitted

**Comment by paradiseduo** [comment]
If you jailbreak with unc0ver
