### ISSUE TITLE
can't connecting to Iphone

### ISSUE THREAD

**Issue by Haxonate** [paradiseduo/appdecrypt#16]
<img width="997" alt="Screenshot 2022-04-12 at 23 25 55" src="https://user-images.githubusercontent.com/43535933/163038426-92e3369a-02f3-41aa-8717-cbc5088855d2.png">

**Comment by paradiseduo** [comment]
???
How do you connect your iphone with ssh?
```
iproxy 2222 22
ssh -p 2222 root@127.0.0.1
```
OR
```
ssh root@192.168.1.35
```

**Comment by Haxonate** [comment]
ssh root@192.168.1.35

**Comment by Haxonate** [comment]
> ???
> 
> How do you connect your iphone with ssh?
> 
> ```
> 
> iproxy 2222 22
> 
> ssh -p 2222 root@127.0.0.1
> 
> ```
> 
> OR
> 
> ```
> 
> ssh root@192.168.1.35
> 
> ```

ssh root@192.168.1.35

**Comment by paradiseduo** [comment]
> > ???
> > How do you connect your iphone with ssh?
> > ```
> > 
> > iproxy 2222 22
> > 
> > ssh -p 2222 root@127.0.0.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > OR
> > ```
> > 
> > ssh root@192.168.1.35
> > ```
> 
> ssh root@192.168.1.35

so, you need
```
scp appdecrypt root@192.168.1.35:/tmp
```
