### ISSUE TITLE
zsh: segmentation fault  ./appdecrypt /Users/madstsk/.myWirdFiles/sideload/HCR2/Payload/hcrwc-iOS.app 

### ISSUE THREAD

**Issue by Maki2007** [paradiseduo/appdecrypt#18]
This is how I have done it.
1. Got an IPA from my iPhone using iMazing
2. Renamed it to a .zip
3. Decompressed the zip file. 
4. Ran the command: `appdecrypt % ./appdecrypt /Users/madstsk/.myWirdFiles/sideload/HCR2/Payload/hcrwc-iOS.app /Users/madstsk/.myWirdFiles/sideload/HCR2-decrypted.app`
5. Got this output: `zsh: segmentation fault  ./appdecrypt /Users/madstsk/.myWirdFiles/sideload/HCR2/Payload/hcrwc-iOS.app`
I have tried to chmod -R 777 the parentfolder.

**Comment by paradiseduo** [comment]
单独执行 ./appdecrypt 会报错吗
