### ISSUE TITLE
release的2.1 iOS版本无法运行，Killed: 9

### ISSUE THREAD

**Issue by 0x5e** [paradiseduo/appdecrypt#19]
2.0版本是可用的，main分支自己编译的版本也是可用的，2.1版本无法运行😅

**Comment by 0x5e** [comment]
是不是没有签名，执行`ldid -S/usr/share/entitlements/ld64.xml appdecrypt`之后可以用了

**Comment by paradiseduo** [comment]
> 是不是没有签名，执行`ldid -S/usr/share/entitlements/ld64.xml appdecrypt`之后可以用了

应该是忘签了😂
