### ISSUE TITLE
This also works perfectly on iOS

### ISSUE THREAD

**Issue by dlevi309** [paradiseduo/appdecrypt#2]
Sorry for creating an issue, I just wanted to let you know that this actually works fully on iOS. Unlike flexdecrypt, it doesn't require spawning the executable, and after a couple of tests to confirm this works, I've been able to decrypt + install the final ipa's with no issues. 

I created a repo with my build configuration and a pre-compiled binary under releases if you wan't to try this out and maybe integrate iOS support into the main repo. https://github.com/dlevi309/appdecrypt-ios

**Comment by bastienjalbert** [comment]
@dlevi309 Thanks for feedback. I'm trying to run the appdecrypt ios binary on TvOS for an iPad app. The output tell me Dump are Success but ipa binary seems still encrypted (running `otool -l IpaBinary | grep crypt` gave me 1). 
Any idea ? That the unique software I found to decrypt an application without running it (I just got a jailbroken Apple Tv currently, to decrypt an iPad ipa)
