### ISSUE TITLE
When I run ./build-macOS_arm.sh I get an error

### ISSUE THREAD

**Issue by TheOnlineUser** [paradiseduo/appdecrypt#27]
When I run ./build-macOS_arm.sh I get the following error:

error: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'

**Comment by paradiseduo** [comment]
![image](https://github.com/paradiseduo/appdecrypt/assets/14846965/f602cbe6-9313-4726-9812-cd80aeae9772)
Please check if you install Xcode.app
