### ISSUE TITLE
DO NOT INSTALL THIS SCRIPT, IT CAN WIPE OUT YOUR FOLDERS IF YOU DONT KNOW WHAT YOU ARE DOING

### ISSUE THREAD

**Issue by MahdeenSky** [paradiseduo/appdecrypt#33]

**Comment by ThatGuy9049** [comment]
Loving the lack of context, mind giving some?

**Comment by csompatt** [comment]
Hi,

appdcerypt wiped all of my data from my desktop. How can I restore them????

**Comment by MahdeenSky** [comment]
> Loving the lack of context, mind giving some?

similar to this https://github.com/paradiseduo/appdecrypt/issues/31

**Comment by csompatt** [comment]
Any chance to restore the wiped files?

**Comment by paradiseduo** [comment]
https://github.com/paradiseduo/appdecrypt/releases/tag/2.4
