### ISSUE TITLE
这个可以实现在mac m1，mac x86上去ios app的壳子吗

### ISSUE THREAD

**Issue by lilili87222** [paradiseduo/appdecrypt#35]
appstore下的app有加密。用这个可以在window上直接对下的ipa去加密吗

**Comment by paradiseduo** [comment]
目前还没有可以脱离苹果设备进行脱壳的办法

**Comment by lilili87222** [comment]
那可以在mac电脑上对ipa进行脱壳吗？
如果可以，是否对mac电脑有架构限制？

**Comment by paradiseduo** [comment]
> 那可以在mac电脑上对ipa进行脱壳吗？ 如果可以，是否对mac电脑有架构限制？

必须是苹果的M系列芯片

**Comment by lilili87222** [comment]
谢谢大佬
