### ISSUE TITLE
Decrypt IPA occur error 

### ISSUE THREAD

**Issue by xellosiris** [paradiseduo/appdecrypt#6]
I tried to decrypt IPA "JW library" but it occurred error. Here is what I done:
1.rename .ipa to zip and unzip it
2.mkdir on Desktop and name it "payload"
3.decrypt app where in unzipped floder

here is error message I received:
<img width="1440" alt="截圖 2021-08-13 上午10 12 58" src="https://user-images.githubusercontent.com/33425166/129295719-275b6bbc-326c-4aa4-96ad-e8804a8ecdda.png">

**Comment by paradiseduo** [comment]
mac with M1？

**Comment by xellosiris** [comment]
No Mac with intel.
But I build in “build-macOS_x86.sh”

從我的iPad傳送

**Comment by paradiseduo** [comment]
> No Mac with intel. But I build in “build-macOS_x86.sh” 如果你喜歡可以說中文，哈 從我的iPad傳送

那用不了的

**Comment by xellosiris** [comment]
可是我留意你的程序有給x86的shell（build-macOS_x86.sh），所以decrypt不能在intel 系統上操作嗎？我只是需要脫殼而已

**Comment by paradiseduo** [comment]
那个文件只是说明可以在x86的电脑上编译成功。

**要脱壳的IPA必须跟脱壳环境对应。**

如果你是从**iPhone**的App Store上下载的ipa，那么必须要在越狱的**iPhone**上使用appdecrypt进行脱壳。

如果你是从**mac**的App Store上下载的ipa，那么必须在装有**M1芯片的mac**上使用appdecrypt进行脱壳。

**Comment by xellosiris** [comment]
原來如此，謝謝你耐心地解答。
另外一個問題請教是，我是利用ipatool下載ipa檔案，這樣算是从mac的App Store上下载的ipa嗎？

**Comment by paradiseduo** [comment]
> 原來如此，謝謝你耐心地解答。
> 另外一個問題請教是，我是利用ipatool下載ipa檔案，這樣算是从mac的App Store上下载的ipa嗎？
> 我想要利用sideload的方式安裝decrypt IPA在m1

不算，ipatool是从iPhone的App Store上下载ipa的。
