### ISSUE TITLE
Failed to copy file - iOS

### ISSUE THREAD

**Issue by Al4ise** [paradiseduo/appdecrypt#8]
Running on iOS (Procursus bootstrap) results in this error occurring:
![IMG_1880](https://user-images.githubusercontent.com/39273158/130202852-d7ad143d-98c6-43e6-a35a-e2ece93c8881.jpg)

**Comment by paradiseduo** [comment]
Give me your command line

**Comment by Al4ise** [comment]
![image](https://user-images.githubusercontent.com/39273158/130230406-5cdc9c24-b5c4-43fe-9f08-3df2396290b8.png)

**Comment by paradiseduo** [comment]
```bash
appdecrypt /var/containers/Bundle/Application/23E4B0B4-7275-46CE-8EEA-18CADE61FDB8 /var/mobile
```

**Comment by Al4ise** [comment]
Oh. Yeah thanks, that works
