### ISSUE TITLE
 xcrun: error: unable to find utility "xctest"

### ISSUE THREAD

**Issue by Master-cai** [paradiseduo/appdecrypt#9]
error: terminated(72): /usr/bin/xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH
![image](https://user-images.githubusercontent.com/37432881/130984851-635a57fd-88c1-4d06-9240-873fe40f0d76.png)

Macos version: 11.5.1
device:  macbook pro with apple silicon(M1)
how to fix it? thx!

**Comment by Am1nCmd** [comment]
Hi, I had similar issue, XCode installed btw 
<img width="682" alt="image" src="https://user-images.githubusercontent.com/15339573/168410660-146230fb-44b9-4250-8ad9-440b694faa4f.png">

**Comment by paradiseduo** [comment]
> Hi, I had similar issue, XCode installed btw <img alt="image" width="682" src="https://user-images.githubusercontent.com/15339573/168410660-146230fb-44b9-4250-8ad9-440b694faa4f.png">

Xcode -> Preferences -> Locations -> Selected the Command Lin Tools: (selected xcode version)
